apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-crud
  name: spring-crud-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-crud
  template:
    metadata:
      labels:
        app: spring-crud
    spec:
      containers:
        - name: spring-crud
          image: sravanscker/crud-spring-boot-app:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
